before_install:
  - npm install -g casperjs
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "npm run test-webserver"
  - sleep 3 # give webserver some time to start
script: npm test
# whitelisting gh-pages https://help.github.com/articles/troubleshooting-github-pages-build-failures/#working-with-continuous-integration-services
branches:
  only:
    - gh-pages
after_script:
  - codeclimate-test-reporter < lcov.info
addons:
    code_climate:
        repo_token: 6a4ed97040a8639e6a1e9efbfd9720fc716b0c5ae991e0ec7a378891b955d6df
