install:
  - npm install
script: grunt mocha
# whitelisting gh-pages https://help.github.com/articles/troubleshooting-github-pages-build-failures/#working-with-continuous-integration-services
branches:
  only:
    - gh-pages
addons:
    code_climate:
        repo_token: 6a4ed97040a8639e6a1e9efbfd9720fc716b0c5ae991e0ec7a378891b955d6df
